title: ""
email: ""
description: ""
baseurl: ""
url: ""

markdown: kramdown

exclude: ["README.md", "CODE_OF_CONDUCT.md", "LICENSE"]

plugins:
- jekyll-autoprefixer
- jekyll-minifier

autoprefixer:
  browsers:
  - last 10 versions

jekyll-minifier:
  uglifier_args:
    harmony: true